### ISSUE TITLE
Make Simple usfm2html convertor

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#194]

**Comment by richmahn** [comment]
Done. I called this repo tx-simple-usfm2html and hooked it up with Travis-CI and Coveralls and deployed to develop and master.
https://github.com/unfoldingWord-dev/tx-simple-usfm2html

**Comment by ethantkoenig** [comment]
How is this different from `tx-usfm2html`?

**Comment by richmahn** [comment]
@ethantkoenig Our USFM style is not standard, from how we do footnotes to how we mark chunks is \s5. As Phil mentioned today, it uses the Paratext USFM markup, rather than standard. Plus, coming from tS with no chapters, paragraphs, etc, we really need it to be forgiving, to to make an HTML file but report errors. When I did try yours with the book of Matthew of the ULB Bible, it failed on \fqa. I didn't investigate further. Was easier to use USFM-Tools which I'm very familiar with and confident with.

tx-simple-usfm2html is not to replace yours if we can get yours to be like how USFM-Tools handles converting from USFM tags to HTML tags, but it does work... simply gets the  UsfmTransform object and calls buildSingleHtm() from the USFM-Tools python library. There's a reason we have been developing it to handle all our USFM needs especially when going to PDF.

So see https://github.com/unfoldingWord-dev/tx-simple-usfm2html to see what we are currently using. Which has converted whole books of the Bible like https://api.unfoldingword.org/ulb/txt/1/ulb-en/41-MAT.usfm which has footnotes (\fqa)
