### ISSUE TITLE
Fix usfm2html for Whole Bible

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#195]
Lambda times out at 5 minutes.

**Comment by ethantkoenig** [comment]
FWIW: I've run a few benchmarking tests on develop, and they seem to indicate that `tx-usfm2html_convert` is 5-6 times faster than `rich-usfm2html_convert`. For instance, running Exodus, Numbers, Deuteronomy, Judges, Nehemiah and Job took 11 seconds on `tx-usfm2html_convert` and 64 seconds with  `rich-usfm2html_convert`.

This is of course under the assumption that `rich-usfm2html_convert` is what is currently being used. I assume this is the case, since `tx-simple-usfm2html_convert` seems to be having dependency issues.

**Comment by richmahn** [comment]
rich-usfm2html is not used at all

**Comment by jag3773** [comment]
Duplicate of #215
