### ISSUE TITLE
Setup Backup Procedure for DynamoDB

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#199]
## Story

As an _admin_|_developer_ I want to have backups setup of our production DynamoDB so that we can restore our database if something goes wrong.

As a _tX user_ I want to have backups setup of our production DynamoDB so that I don't lose all my data if something goes wrong.

## Notes

Write a hook in the Lambda pipeline to query the Door43-Catalog organization and ensure that all repos are in the database any time it receives a webhook.

Essentially this is not a backup and restore procedure but rather a start over procedure.

**Comment by neutrinog** [comment]
@jag3773 I had to stop using the `d43-catalog-production` table because the size of the catalog has grown enough to exceed the maximum write limit for a single item (400KB).

If we want to keep backups of current/past catalogs we'll need to store them in an s3 bucket.

**Note:**
 We do have a working fork lamda function on a 5 min schedule that will pull in un-processed repos. Rebuilding the entire catalog from scratch can take around 10-15 minutes.

**Comment by neutrinog** [comment]
We will set up a trigger on the catalog (stored in the api bucket) that will create a backup.

**Comment by jag3773** [comment]
Versioning is now enabled on the S3 bucket so goal achieved ;)
