### ISSUE TITLE
Metrics: Views Per Repo

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#21]
## Story

As an _admin_|_user_ I want to see how many times a particular repository has been viewed so that I know how popular it is.

Update: to use Javascript to update the database.  See https://www.google.com/search?q=javascript+query+dynamodb&rlz=1C5CHFA_enUS690US690&oq=javascript+query+dyn&aqs=chrome.0.0j69i57j0l4.7279j0j7&sourceid=chrome&ie=UTF-8

## Notes

This should work similar to views on a YouTube video.  Note that this applies to the rendered HTML pages of the repos.  Views should be counted for a repo as a whole and also for each commit.

Should be counting number of hits/pageviews.

Data can be pulled either from Google Analytics or from CloudFront web log file.

If using CloudFront log files, write a lambda function that processes them whenever a log file is saved to the S3 bucket at logs.door43.org/door43.org/.

Data should go into DB in #446.

Research phase is time boxed at 1 hour.

**Comment by PhotoNomad0** [comment]
Notes:
- read from manifest table
- sum up the views of every revision for a repo

**Comment by PhotoNomad0** [comment]
@jag3773 - I am beginning to think that using a lambda to increment/read the page counts is best.  Most of the javascript examples are using server side javascript (where they can hide the access tokens).  The few client side examples the user is logged into AWS using those credentials or some other form of oath.  Also using a lambda would allow us to implement the increment as a mutex operation rather than a read followed by an update.

**Comment by jag3773** [comment]
That's fine Bruce, however we can make it work best.
