### ISSUE TITLE
Research PDF, DOCX, ePub Conversion Options

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#210]
We are planning to support PDF, DOCX, and ePub downloads for each of our projects.  This task is to research what tools might meet the following criteria:

* [ ] Run on Lambda with minimal fuss
* [ ] Support as many of the above outputs as possible
* [ ] Support non-roman scripts

Time boxed at 2 hours.

## Definition of Done

This is a research task that should end with a description of the relevant options and a recommendation of which one to try first.

**Comment by richmahn** [comment]
**PDF**
Just for reference, I found only wkhtmltopdf  (http://wkhtmltopdf.org/) works without needing to have a OS's display to generate the PDF (doesn't need the X11 libraries or whatever) which made it the choice for lambda functions, as there is even a Lambda example written which I played with back before we were doing Scrum, the tx-html2pdf converter I threw together. I don't think there is anything else that could handle Lambda, and is what worked best with tA when we generated its PDF from a regular bash script. 

See https://github.com/lubos/aws-lambda-wkhtmltopdf for a wrapper like my tx-md2pdf converter borrowed from.

**ePub**
That may mean we have to find another tool for ePub, such as Calibre (http://calibre-ebook.com). See https://github.com/kovidgoyal/calibre/blob/614d94496efdcf960871429e1c090c56d2018f68/manual/news.rst#tips-for-developing-new-recipes for command-line use

**Comment by ethantkoenig** [comment]
## 1. Pandoc

It seems to be possible to use pandoc in Lambda (see [here](https://claudiajs.com/tutorials/pandoc-lambda.html)). Assuming that pandoc's output are of sufficient quality, this seems to be the best option. It supports docx, pdf, and epub outputs.

From running pandoc locally, it supports non-ASCII characters for both docx and pdf outputs. I haven't

We will have to upload a binary to AWS (probably two, since we'll also need xelatex).

## 2. Calibre

The second best choice seems to be calibre. It also supports docx, pdf, and epub outputs. It would also involve uploading a binary to Lambda.

I slightly prefer pandoc to calibre, since pandoc seems to be a more general utility, and there is a documented procedure for using it in Lambda.

## Alternatives

For the sake of completeness, here are my other findings:

### PDF

There are a bunch of HTML-to-PDF conversion tools. The only Rich mentioned above, [wkhtmltopdf](http://wkhtmltopdf.org/), seems quite robust.

### Docx

The best library I could find was [html-docx-js](https://github.com/evidenceprime/html-docx-js). Not sure how well it handles non-ASCII characters. Its outputs are not supported by Microsoft Word for Mac, LibreOffice, or Google Docs.

There's also [zopyx.convert](https://pypi.python.org/pypi/zopyx.convert2/2.4.5), but it has so many external dependencies that it would be a hassle getting it to work in Lambda.

### Epub

There a few options other than pandoc and calibre. There's [web2epub](https://github.com/rupeshk/web2epub), but it only supports epub outputs, and doesn't seem to be actively maintained.

## Next Steps

If we do upload binaries to Lambda, we should ensure there are compatible with Amazon's version of Linux (see [here](https://aws.amazon.com/blogs/compute/running-executables-in-aws-lambda/) for more). I would be happy to investigate this further if necessary.

**Comment by jag3773** [comment]
To be considered:

https://github.com/simoncozens/sile/
https://www.npmjs.com/package/markdown-pdf
