### ISSUE TITLE
Make RTL Languages Display RTL

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#324]
## Story

As a *user* I want my RTL language display RTL so that it looks correct.

## Notes

For example, https://live.door43.org/u/jdwood/glk_act_text_reg/ should be RTL.  Grab the language direction information from https://td.unfoldingword.org/exports/langnames.json

**Comment by PhotoNomad0** [comment]
It appears that in titles just adding the attribute 'dir="auto"' would address the issue. But the chunks are different in each verse number starts with an Arabic number which would throw off the browser since it would start laying out in ltr order and the verse marker would be on the wrong side. In this case you would have to add the attribute 'dir="rtl"' when the language is RTL. The direction information should be in the manifest.

Information about RTL support in HTML: https://www.w3.org/International/articles/inline-bidi-markup/

**Comment by PhotoNomad0** [comment]
a couple more projects for testing:
- https://git.door43.org/photonomad0/ar_eph_text_ulb => https://live.door43.org/u/photonomad0/ar_eph_text_ulb/200ba03344/
- https://git.door43.org/photonomad0/ar_obs_text_obs => https://live.door43.org/u/photonomad0/ar_obs_text_obs/44104712a8/
