### ISSUE TITLE
Merge tw-en into en-tw and Make a Correct RC

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#341]
## Story

As a *user* I want to a consistent & accurate source location for tW so that I know where to find the latest and fork if needed.

## Notes

Before we moved tW into Gogs following the new RC format, we had copied it over to [tw-en](https://git.door43.org/Door43/tw-en) to try to make revision history more viewable.  Now we have two repos purporting to hold the source for English tW.

The [en-tw](https://git.door43.org/Door43/en-tw) repo needs to be the master and should have the revision history of the previous repo if possible.  In other words, it would be great if we could have all the tagged versions from tw-en merged into en-tw so that there is one place to see all the revisions.

In addition, the en-tw repo is not a valid RC right now, we should take this opportunity and make it so.

End goal: [en-tw](https://git.door43.org/Door43/en-tw) is a valid RC and it has versions 1-4 tagged correctly as Releases.

**Comment by neutrinog** [comment]
began writing my conversion script. Right now I just need to figure out the difference between `en:obe:other:zadok` and `en:obe:kt:temple`. Notice the `other` and `kt`.

**Comment by neutrinog** [comment]
@jag3773  also, in converting this I would like to propose anther change to the spec.
The dictionary rc type has a field in the config.yaml named `def_title` that holds the title placed above the definition of the term e.g.

* Definition
* Facts

However, I think the need for that was mostly due to legacy stuff. If we let the `def_title` remain in the content then we can drop this field from the config. This would be ideal since the config is designed to handle associations not translations.

**Comment by jag3773** [comment]
@neutrinog I don't see what you are referring to with the `config.yaml` file.  It sounds reasonable though!  Can you create a PR against the RC spec so i can see what you mean?

Also, "other" and "kt" should go away.  Those folders should just merged into the standard content folder.

Should "bible" be a project as listed here: https://git.door43.org/Door43/registry#projects ?

**Comment by neutrinog** [comment]
@jag3773 to your last question yes `bible` should be listed as a project.

**Comment by neutrinog** [comment]
@jag3773 how should I parse the links under **Bible References:** in https://git.door43.org/joel/en-tw/src/master/content/other/stiffnecked.md?

Those links point to a page that has lots of stuff:

* passage snippet
* tW
* tN
* tQ

**Comment by neutrinog** [comment]
Found a direct link to OBS. https://door43.org/en/obs/notes/frames/22-07
Do we want to keep those?

**Comment by neutrinog** [comment]
@jag3773 there are some links within tW that point to tN. For example:

```
* [Habakkuk 01:1-2](https://door43.org/en/bible/notes/hab/01/01)
```
Do you want me to title the links differently now that notes will no longer contain the passage text? Or I could make these links title-less e.g. `[[en/tn/hab/help/01/01]]`.

**Comment by neutrinog** [comment]
Here's are a list of branches for the different version of tW. I cannot submit a pull request because we'll need to re-write the entire history once these are approved.

* [v1](https://git.door43.org/joel/tw-en/src/v1_rc)
* [v2](https://git.door43.org/joel/tw-en/src/v2_rc)
* v3
* v4
* v5

**Comment by neutrinog** [comment]
Notes to self. in the en-tw repo there are some changes in how the data is structured.

Related words have several formats
* `(See also`
* `(See` - could be words or tA articles.

translation suggestion have two formats
* `##Translation Suggestions`
* `(Translation suggestions`

The aliases are in the title delimited by commas where the first one is the real title
e.g. `# evil, wicked, wickedness #`. `evil` is the title and the aliases are `wicked` and `wickedness`.

**Comment by neutrinog** [comment]
@jag3773 it appears that in current forms of tW the aliases are always written inline with the title of the world. e.g. `# God the Father, heavenly Father, Father`. Before there was a separate aliases section in the file.

Initially I was trying to work around this but now I'm re-thinking the rc0.2 spec. In the current spec we store inside the config.yaml the following info:

* title
* related words
* aliases
* examples

However, with support for [linking](http://resource-container.readthedocs.io/en/latest/linking.html) inside between and inside containers, we could completely leave out the config.yaml for translationWords. This would of course simplify them a lot. My reasoning is as follows:

* tS doesn't used the aliases
* examples and related words are just converted into links and displayed in the description so we may as well leave them there in the first place.
* The title doesn't need to be stored in multiple places.
* It means the least amount of change for the current form of tW.
* Things used in lists like the title can always be cached by the app to reduce the i/o load.

Therefore I propose we alter the dict RC type to:

* remove the config.yaml
* expand definition to suggest placing aliases in the title
* expand definition to suggest placing links within the description for related words and examples.

**Comment by neutrinog** [comment]
this would also fix some ambiguity we currently have with linking examples for tW.

**Comment by neutrinog** [comment]
Going down the rabbit hole a little bit. Here's an example from a mail client I use (Nylas). Notice the drag-able tags. If we do end up translating tW we could build a UI that supports drag-able tags for examples and related words.

![merge tags example](https://cloud.githubusercontent.com/assets/166412/24920648/d0a5cd40-1e9c-11e7-85a6-9a87eb89635b.png)

**Comment by neutrinog** [comment]
Notes from meeting with @jag3773 Perry and @klappy:

Eventually we'll re-purpose the config.yaml to store the following info:
* proper noun - Boolean to indicate if this is a proper noun.
* occurrences - An exhaustive list of occurrences of the word. These will be RC links.

The markdown file will contain the following:
* Aliases (RC links)
* Examples (RC links)
* Strong's numbers
* Maybe parts of speech

 Bible links can have verse granularity.

Since some people are already using the current RC spec we will tag a beta release `rc0.2-beta` as a reference and continue development on an `rc0.3` branch.

---

What this means for us now is the config.yaml will go away (since it'll be empty) while aliases and examples will remain in the markdown file.

**Comment by neutrinog** [comment]
so tW v1-5 will use rc0.2 and then the master branch will use rc0.3.

**Comment by neutrinog** [comment]
@jag3773 I tried tagging the [RC Repo](https://github.com/unfoldingWord-dev/Resource-Container) but it's not getting re-built or it doesn't like my terminology. I accidentally tagged it as 0.2 not 0.2b1 before so I see the 0.2 on readthedocs but not the corrected version. Can look at it and fix all my mistakes for me? :)

**Comment by neutrinog** [comment]
This issue was getting rather noisy so I split pieces into their own issues as appropriate. 

The original purpose of this issue is ready for review at https://git.door43.org/joel/en-tw.
Once approved we'll need to:
* [ ] delete all tags in https://git.door43.org/Door43/en-tw
* [ ] force push my repo to https://git.door43.org/Door43/en-tw
* [ ] push all tags from my repo to https://git.door43.org/Door43/en-tw

Before doing so we should tell everyone not to touch the repo so we can get the most recent updates and merge them into the converted content.

**Comment by neutrinog** [comment]
Some bugs have been fixed in tW. We should pull those into the master branch before merging this in.

**Comment by neutrinog** [comment]
@jag3773 we can do the same thing here as in  #342. That is, we don't have to re-write the history, but simply delete all the files and continue on top of it. This'll make it easier for people to continue using this repo without re-cloning.

I'll make a PR and let you know when ready.

**Comment by neutrinog** [comment]
@jag3773 This is now ready for review. See the pull request at https://git.door43.org/Door43/en-tw/pulls/23.

**Comment by neutrinog** [comment]
this has been merged in.
