### ISSUE TITLE
Lang Page: Search for language code

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#443]
User selection in #444 .  This should query the language code field in the database.

Multiple language code selections are ORed together.

**Comment by PhotoNomad0** [comment]
@jag3773 - OK, have the language query working from JS, do we want to set  a limit for how many item returned?

**Comment by PhotoNomad0** [comment]
> @jag3773 - OK, have the language query working from JS, do we want to set a limit for how many items are returned on a match?

@jag3773 - Also, looking at the current UI implementation (http://test-door43.org.s3-website-us-west-2.amazonaws.com/en/) there is just a single text field.  How did you envision the user entering a list of languages to search?  I am guessing that this issue is javascript only, that the UI for multi-selections is outside the scope for this issue.

**Comment by jag3773** [comment]
UI build is in #444.

**Comment by PhotoNomad0** [comment]
At request of @richmahn added optional parameters for repo_name, user_name, and resources.

**Comment by richmahn** [comment]
I have completed #444 with my PR #606. Bruce just has to call `getLanguageCodesToFilter()` for an array of language codes.
