### ISSUE TITLE
Missing Text in ULB Footnote(s)

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/door43.org#483]
As a User of the API (tS app) I need to receive all the data (text) that the content team supplies.  We have found a scenario where this is not happening.  It occurs when the "\fqb" tag is used in the USFM content files.  It appears that the goal is to mark the end of a quote, paired with a "\fqa" tag.  When this occurs, all text following the "b" tag is cut during the parsing process into USX.  It has been suggested that it should instead be a "\fqa*" tag to close the quote.  That may be, and maybe the content needs to be updated, but you might also want to make sure data isn't being stripped when it shouldn't if there are "\fqb" tags.  Here is a specific example from 1 Chronicles 1 verse 6.  According to Christine, the USFM file shows this, indicating the text for a footnote with the proper names in quotes:

\f + \ft Some versions have \fqa Diphath \fqb instead of \fqa Riphath \fqb . However, \fqa Diphath \fqb was probably a mispelling. Many ancient copies correct it to \fqa Riphath \fqb in order to make it agree with the same name in Gen. 10:2. \f*

In the resource container that is created for the tS apps to use, the text arrives looking like this:

<note caller="+" style="f">

  <char style="ft">Some versions have </char>

  <char style="fqa">Diphath </char>

  <char style="fqa">Riphath </char>

  <char style="fqa">Diphath </char>

  <char style="fqa">Riphath </char>

</note>

Which creates a footnote for the user that reads:

Some version have Diphath Riphath Diphath Riphath

API location for this is https://api.unfoldingword.org/ts/txt/2/1ch/en/ulb/source.json .  Source location is https://github.com/Door43/ulb-en/blob/master/13-1CH/01.usfm#L15 .  USFM to USX conversion code might be imported from https://github.com/unfoldingWord-dev/USFM-Tools.

**Comment by ChrisJarka** [comment]
Here is a conversation from Slack #resources channel dated 3/13/17:
Phil Hopper [7:51 PM] 
@channel A "bug" has been discovered in ULB that is causing data loss in translationStudio. The issue is being caused by the use of `\fqb` as a closer for `\fqa` instead of the proper closer which is `\fqa*`. It would be greatly appreciated if someone could make this change everywhere the faulty marker is used, both in ULB and UDB. More information can be found here: http://ubsicap.github.io/usfm/characters/nesting.html

David Statezni [8:03 PM] 
@tom_warren Is this something that you would like me to do a global replace on??

Richard Mahn [8:14 PM] 
@phil: We probably also should verify in our USFM-Tools that fqa* is parsed properly both for HTML and USX conversion. 
That is, it takes text after it that it puts into the output.

Phil Hopper [9:43 PM] 
@rich I already did with USX. It works correctly with `\fqa*`.

**Comment by jag3773** [comment]
Probably need to re-publish the ULB again to get these fixes into the API.
