### ISSUE TITLE
Handle a the download of a project better if file doesn't exit

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#597]
## Story

As a user of live.door43.org I want to either not see a Download button if that revision's tx-client-webhook/preconvert .zip file doesn't exist, or a better error page than "Access denied" as the file just doesn't exist.

Example: go to https://live.door43.org/u/Door43/en-obs/e0a9332e96/index.html and click Download->MD.

**Comment by jag3773** [comment]
I'm reconsidering this download link and wondering if it would be better for us to point directly at the DCS zip ball for the revision in question.  What do you think @richmahn and @PhotoNomad0 ?

**Comment by richmahn** [comment]
Then it isn't "processed", such as USFM chapters or chunks being merged together for a Bible book, or if OBS is still by each frame, it will have a lot of files that you really can't do anything with unless you also write something to massage it. So not sure about that. But I do think we need to be putting these pre-convert zip files in the cdn.door43.org bucket as tx-client-webhook was never meant to be a bucket for the public, and put the zip file in its project directory (e.g. cdn.door43.org/u/Door43/en_obs/41das93az.zip)

**Comment by PhotoNomad0** [comment]
So far it looks like the only way in pure JS to check for the existence of a file at an url is to download it.  Not a good solution download the source every time the page is opened.

It looks like we can use the window.onerror to capture download errors and display an alert, but it may not work on all browsers.

Maybe we could use AWS API to check for the existence of the file on the cdn in advance?

**Comment by PhotoNomad0** [comment]
@richmahn - have had no success checking for the presence of the preconvert file without downloading.  Have tried using S3 API for JS and also tried doing an AJAX "HEAD" requet.  In both cases I keep running into crossdomain exceptions such as:

`XMLHttpRequest cannot load https://s3-us-west-2.amazonaws.com/test-tx-webhook-client/preconvert/39a099622d.zip. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://test-door43.org.s3-website-us-west-2.amazonaws.com' is therefore not allowed access.`

I have tried updating the CORS Configuration of AllowedOrigin for both S3 buckets, but it didn't help.  May have to just do lambda because of browser security issues.

**Comment by richmahn** [comment]
@PhotoNomad0 Hmm...ok. Thanks for researching that.
