### ISSUE TITLE
Make en_ulb and en_udb Convert

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#604]
## Story

As an *editor* I want to see the Bible texts in pretty form so that I can easily review them.

## Notes

Neither https://git.door43.org/Door43/en_ulb or https://git.door43.org/Door43/en_udb are converting properly.

These DCS issues need updated when this is complete: https://git.door43.org/Door43/en_ulb/issues/1060 and https://git.door43.org/Door43/en_udb/issues/265.

**Comment by jag3773** [comment]
@PhotoNomad0 has noted that this is likely due to an out of space problem when running the conversion.  Possible fix would be to clean up tmp files while conversion is in process?

**Comment by jag3773** [comment]
See comment at https://github.com/unfoldingWord-dev/door43.org/issues/556#issuecomment-308591115 .

Also see https://serifandsemaphore.io/aws-lambda-going-beyond-5-minutes-34e381e71231 if applicable.

**Comment by PhotoNomad0** [comment]
Possible way to increase memory:  https://stackoverflow.com/questions/37987576/how-to-scale-lambda-when-tmp-is-reused

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 has noted that this is likely due to an out of space problem when running the conversion. Possible fix would be to clean up tmp files while conversion is in process?

ActuallyIt looks like it is the deploy process that is the culprit.

**Comment by PhotoNomad0** [comment]
Ran a conversion and looked at the logs. It looks like for https://git.door43.org/Door43/en_ulb.git the converter is failing to find any of the usfm books in the repo.

**Comment by richmahn** [comment]
I think it now can't find books/usfm file because of the new manifest .yaml file that was added 3 weeks ago. Will have to fix that too.

**Comment by richmahn** [comment]
I see right away that the "path" for the "project" in the manifest is a file...I never assumed files before. I would have thought all these books are one project, thus the path would just be ./. Should we assume a project can also be a single file? What's the purpose of that? I don't combine USFM files together, only chunks. I would think this was a set of books, a single project, path being ./. @jag3773 ?

**Comment by jag3773** [comment]
@richmahn Each book of the Bible is it's own project.  The RC spec allows combining multiple projects into 1 RC, this is called the `bundle` type.  See http://resource-container.readthedocs.io/en/latest/container_types.html#bundle-bundle .  The ULB/UDB follows this format.

**Comment by richmahn** [comment]
Ok, then will make an issue for this. I knew each book could be a project, but thought it would have its own directory such as GEN/ or 01-GEN/, where as a Bible bundle was all the books in one directory as USFM files.

**Comment by PhotoNomad0** [comment]
Note: tested a whole bible conversion with https://git.door43.org/tx-manager-test-data/bible_ru which doesn't have a manifest. And it failed to complete.  It looks like we have already made fixes to the deploy so that memory is cleaned up and it only runs when all the parts have completed.

There are several issues on doing a full bible:
- it breaks on non-bible usfm files (e.g. license.usfm)
- several times tx_client_callback did not get called after tx_convert_usfm2html completed, but there is nothing in the log that indicates a failure.

Therefore even when we fix the manifest issue, we will still need to work on the conversion for doing a whole bible.

**Comment by PhotoNomad0** [comment]
Update 7/16: tested a whole bible conversion with https://git.door43.org/tx-manager-test-data/bible_ru which doesn't have a manifest. And it failed to complete.  It looks like we have already made fixes to the deploy so that memory is cleaned up and it only runs when all the parts have completed.

There are several issues on doing a full bible:
- it breaks on non-bible usfm files (e.g. license.usfm)
- one time tx_client_callback did not get called after tx_convert_usfm2html completed.  Discovered timeout in the lambda function.  During conversion of the whole bibile tx_start_job lambda is started 11 times for the 67 books.  Discovered that database changes calls the lambda in batches (currently set to 100).  Unfortunately during one batch we got 21 start conversion calls which resulted in a timeout (5 minutes). Setting this batch size down to 9 max allows conversion to complete without timing out the lambda.  But making this change exposes another issue:
- deploy times out after about 5 OT books (Gen to Deut).  So I will modify deploy to update after each book conversion rather than waiting for all to complete first.  This should also make it more failure tolerant.

**Comment by PhotoNomad0** [comment]
Also fixed problem that temp files were not being cleaned up in converter.  Now can convert a whole Bible.

**Comment by PhotoNomad0** [comment]
Still was seeing periodic timeout in the tx_start_job lambda function. Set this batch size down to 5 max to allow conversions to complete without timing out the lambda.

Addressed deploy time outs by incrementally templating files as they are converted and saving title and chapter information.  Then after all the files are templated, I reopen all the files to setup the right navigation using the saved title and chapter information.

Was able to get the whole bible to convert and deploy with proper navigation on webpage.
