### ISSUE TITLE
Problem with tpi_obs

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/door43.org#618]
As a support person, I want to help people who need to edit the Tok Pisin OBS. Unfortunately, the repo in the catalog generates an error when attempting to load it in translationStudio Desktop. The error in the console reads "Error: ENOENT: no such file or directory" pointing at the manifest.json file.

The repo is here: https://git.door43.org/Door43-Catalog/tpi_obs

**Comment by jag3773** [comment]
@mondele I'm looking into this.

Appears that the format of the manifest/package information file is not what tS is expecting.  tS doesn't yet support the latest RC format, so I'm trying to track down the latest version that it does support.  Once I figure that out I can modify the manifest/package file to be what it is expecting and it should be importable.

**Comment by jag3773** [comment]
@mondele  Here is a bit of info on what formats are floating around (from @neutrinog ):

> there are several formats floating around:
> *1* tS source (rc0.1 compressed with tstudio ext or uncompressed )
> *2* tS project (like https://git.door43.org/joel/en-x-demo2_php_text_reg)
> *3* modern RC (rc0.2 which tS doesn't support at all)

I can successfully load a modified version of https://git.door43.org/Door43-Catalog/tpi_obs using the Import Source Text dialogue.  However, that's not really helpful because it is already in the app as a source text.

I'm guessing what you really want is to be able to edit the `tpi` translation.

With the current limitations I would recommend one of the following:

1. If the edits to be made are small and/or sporadic, follow the Suggest an Edit/Fork and Pull model on DCS described here: http://help.door43.org/en/knowledgebase/5-general-questions/docs/39-suggest-an-edit-on-dcs
1. If the edits to be made are large, use tS and load `tpi` in the source text pane and then copy, paste, and modify.

**Comment by mondele** [comment]
I understand. Thanks.
