### ISSUE TITLE
Add Page for old DokuWiki Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#633]
## Story

As a *user* I want to know what happened to the previous door43.org site so that I don't get confused.

## Notes

We need a page that explains the transition from DokuWiki door43.org to the live site door43.org, with information detailing at least the following:

* How to get to the old DW site ( dw.door43.org )
* How to get content migrated from the old DW site to DCS + live site
* How to find content in new live site

**Comment by jag3773** [comment]
@ChrisJarka Can you list here any other information that you think would be helpful for users to know?

**Comment by ChrisJarka** [comment]
@jag3773 I would think this minor change would be good

How to get to the old DW site ( dw.door43.org ) **_with a notice to NOT edit the dw.door43.org information._**


Curious - can the information be posted on the redirect page? I forget if you can determine how long the redirect page is displayed.

**Comment by jag3773** [comment]
@ChrisJarka Can you please review http://dev-door43.org.s3-website-us-west-2.amazonaws.com/en/about/new_door43.html and note suggestions for improvements here?

**Comment by ChrisJarka** [comment]
Can the links be set to open a new tab/window?

The icon in the top left is not showing. 
![image](https://user-images.githubusercontent.com/9850185/29725729-1ee519b6-899b-11e7-802b-419f413d25d9.png)

How about bringing the WHAT HAPPENED TO ... section to under the first two lines. 

I think basically since this page is for the 'NEW DOOR43" maybe the 'EDITING CONTENT' section is too much information and 'objective creep' from the reason for the page?


Oh - and now with time - the 43 icon shows in the top left corner.

The link for "this new Door43 site" goes to the wiki.

**EDITING CONTENT INFORMATION**
It would be nice if the link to 'DCS Knowledgebase' went directly to the http://help.door43.org/en/docs/39-suggest-an-edit-on-dcs instead of the http://help.door43.org/en/knowledgebase/15-door43-content-service page. From the latter page it might be hard to figure out where to go for the necessary information. (BTW - you are suggesting a fork-PR to make suggestions and not issues?)

Since the sentence says 'try one of these:' I would think that the links would take me to the instructions on how to edit content in those tools.

WHAT ABOUT CHANGING THIS:
You can also use a translation tool such as translationStudio, translationCore or Autograph; and use its sync or upload feature to contribute. Try one of these:  

TO:
You can also use a translation tool such as translationStudio, translationCore or Autograph; and use its sync or upload feature to contribute.  (Can you do inline links so that the links that are in the bullet list are in the sentence?)
Here are the instructions on how to sync or upload feature of:

- translationStudio - with link to http://help.door43.org/en/knowledgebase/9-translationstudio/docs/32-upload-or-export
- translationCore - with link to (does helpdesk have such a page for tC?)
- Autographa - with link to ???

BTW - The link to Autographa is not valid.

WHAT HAPPENED TO .... section
_All of the content from the old wiki has been migrated into DCS. You can search for content using the search box on the Browse page._

I find the links in this section to confuse me - to me it sounds like the link for the DCS and the Browse page goes to the same site. But they don't look the same and so it might confuse the end user. 

How to fix? Good question. Because - there would need to be so much more explanation.
The need to add in that the way to go from live.door43 to the DCS is to click on the inconspicuous link of 'See on DCS.'

**Comment by jag3773** [comment]
@ChrisJarka can you review https://dev.door43.org/en/about/new_door43/ again?

**Comment by ChrisJarka** [comment]
So much better! Simpler and gets to the point.
Can the links be 'open to new window/tab'?
You might want to remove the link in this statement - "up on this new Door43 site."
This information is really on the page twice - "Use the Browse page to find content." - and is probably best served later in the page.

Would you consider switching the order of these two sentences?
_The old DokuWiki site is still available in read-only mode at https://dw.door43.org.
All of the content from the old wiki has been migrated to this new site, you can use the Browse page to find it._

So that it would be:
_All of the content from the old wiki has been migrated to this new site, you can use the Browse page to find it.
The old DokuWiki site is still available in read-only mode at https://dw.door43.org._

Since 1) the sentence starting with 'all of the content' answers the question and 2) the end user will be more concerned about where to find the new content and might be secondly interested in where the read-only is located.
