### ISSUE TITLE
If a tX conversion never completes, project page keeps reloading. Need to give a failure message.

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#639]
## Story

As a user of door43.org, I don't want to think my conversion is still in progress even days later. Currently if a tX conversion fails, the page keeps reloading and says "Conversion requested..."  (e.g. https://live.door43.org/u/Door43/en_tn/cc96e2a7de/) and the view count goes up one 1 every 10 seconds since we reload the page if conversion is in progress.

We need to either have a script that goes through and update the build_log.json of the revision/commit for all unfinished conversions and best tell why it failed (update the error message array), and/or in the javascript have it look to see if it has been more than 20 minutes or so and state there was an error and remove the "Conversion requested..." message and don't let the page keep refreshing/reloading.

**Comment by PhotoNomad0** [comment]
@jag3773 @richmahn - see a couple possibilities here:
- change javascript to just query build_log.json every 10 seconds rather than reloading the page.  Then we only reload the page if the status changes.
- change the javascript to call a lambda that we can query for build status if not finished.  The advantage of doing in a lambda is that it could update the build status in the table and build_log.json to an error if it has been too long.

**Comment by PhotoNomad0** [comment]
Notes: Richard suggests we check job database instead of build_log.json since it would be more up to date.
