### ISSUE TITLE
Add Menu Links to Footer

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#67]
## Story

I want the links in the header to show up in the footer, just like we have setup on the uW website.

## Notes

I added the footer-menu.html in this commit 77a682eaa4c4fe74cc4a8a6b3b660efb796aea4e but when I tried including it in footer.html I got this error:

```
  Liquid Exception: undefined method `each' for nil:NilClass in _layouts/default.html
jekyll 3.2.0 | Error:  undefined method `each' for nil:NilClass
```

**Comment by PhotoNomad0** [comment]
@richmahn @jag3773 - running into issue with putting header menu into footer: the about is a dropdown menu that extends below bottom of the page. Fortunately you can then scroll further down at that point, but it is not obvious to the user that there is more than one item in the dropdown.

**Comment by PhotoNomad0** [comment]
Got feedback from @richmahn that the footer menu is to be flat with just the about and contact items.  But the header is already hierarchical: https://github.com/unfoldingWord-dev/door43.org/blob/develop/_data/main-menu.yml.  This does not look good on the footer.  So My current interpretation of "just like" the header is that  the footer should have "about" and "contact" items, but that "about" should be flat instead of a drop down like the header is.

Is this correct?

**Comment by richmahn** [comment]
@PhotoNomad0 I am just going by what I see in the unfoldingword.github.io repo, but I assume that is the design, to just have the top level menu items in the footer.

**Comment by jag3773** [comment]
@PhotoNomad0 Correct, just like the uW site only has the top level menu items (see https://unfoldingword.org/academy/ for an example).
