### ISSUE TITLE
Add tA Links into tN

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#676]
In order to for tC to consume and categorize the notes in tN we need them to be tagged with a tA article.  The notes that do not have a tA tag generally follow patterns that we can use to programmatically insert the tags.

@ChrisJarka will provide the pattern here and we'll work on adding them to en_tn.

**Comment by ChrisJarka** [comment]
For every note that has 'AT:' there is this explanation on https://git.door43.org/Door43/en_ta/src/master/translate/resources-alter/01.md:

_An alternate translation is a possible way to change the form of the ULB in case the target language prefers or needs a different form. The alternate translation should only be used when the ULB form or content would give a wrong meaning, or would be unclear or unnatural._

_The alternate translation suggestion may involve, for example, stating implicit information clearly, changing passive voice to active, or rewording rhetorical questions as statements. The notes often explain why there is an alternate translation and have a link to a page that explains the topic._

For almost all of the ATs there should be a link to a tA Topic.

**Comment by ChrisJarka** [comment]
For every note that has an **alternate meaning** offered there is this explanation on https://git.door43.org/Door43/en_ta/src/master/translate/resources-alterm/01.md:

_Alternate meanings refer to when Bible scholars have different understandings of what a word or phrase means._

_The note will have the ULB text followed by an explanation starting with the words "Possible meanings are." The meanings are numbered, and the first one is the one that most Bible scholars consider to be correct. If a meaning is given in a way that it can be used as a translation, it will have quote marks around it._

_The translator needs to decide which meaning to translate. Translators may choose the first meaning, or they may choose one of the other meanings if the people in their community use and respect another Bible version that has one of those other meanings._

**Comment by ChrisJarka** [comment]
For notes that have "(UDB)" in the note there is this page: https://git.door43.org/Door43/en_ta/src/master/translate/resources-clarify/01.md

_Sometimes a Note suggests a translation from the UDB. In that case the text from the UDB will be followed by "(UDB)."_

And this example:

- he fell on his face - "he knelt and touched the ground with his face" or "he bowed down to the ground" (UDB)

**Comment by ChrisJarka** [comment]
**Connecting Statement** and **General Information** notes

Described on this page:
https://git.door43.org/Door43/en_ta/src/master/translate/resources-connect/01.md

With this explanation of the syntax used:
Sometimes, at the top of the list of notes, there are notes that start with Connecting Statement or General Information.

_A connecting statement tells how the scripture in a chunk is related to scripture in earlier chunks._

_A general information note tells about issues in the chunk that cover more than one phrase._

_Both types of notes are to help you understand the passage better and be aware of issues that you might need to address in translation._

**Comment by ChrisJarka** [comment]
**Definitions**:

See: https://git.door43.org/Door43/en_ta/src/master/translate/resources-def/01.md

_Sometimes you may not know what a word in the ULB means. The notes may have a definition or a description of the word or phrase to help you understand what it means._

The explanation of the formatting is:
_Simple definitions of words or phrases are added without quotes or sentence format._

Examples:

- marketplace - a large, open-air area where people would come to sell their goods
- flute - a long, hollow musical instrument which is played by blowing air in or over one end

**Comment by ChrisJarka** [comment]
Notes that Explain

Page that describes: https://git.door43.org/Door43/en_ta/src/master/translate/resources-eplain/01.md

_Sometimes you may not know what a word or phrase means in the ULB, and it may also be used in the UDB. In this case, it will be explained in the notes. These explanations are meant to help you understand the word or phrase. Do not translate the explanations into your Bible. Use them to help you understand the meaning so you can translate the Bible text correctly._

Definition of the formatting of Notes that Explain: 

_Simple explanations about words or phrases are written as full sentences. They begin with a capital letter and end with a period (".")._

**Comment by ChrisJarka** [comment]
**Notes that describe Direct and Indirect Quotes**

Page reference: https://git.door43.org/Door43/en_ta/src/master/translate/resources-iordquote/01.md

_There are two kinds of quotations: direct quotation and indirect quotation. When translating a quotation, translators need to decide whether to translate it as a direct quotation or an indirect quotation. (See: Direct and Indirect Quotations)_

_When there is a direct or indirect quote in the ULB, the notes may have an option for translating it as the other kind of quote. The translation suggestion may start with "It can be translated as a direct quote:" or "It can be translated as an indirect quote:" and it will be followed by that kind of quote. This will be followed by a link to the information page called "Direct and Indirect Quotations" that explains both kinds of quotations._

_There may be a note about direct and indirect quotes when a quote has another quote inside of it, because these can be confusing. In some languages it may be more natural to translate one of these quotes with a direct quote and the other quote with an indirect quote. The note will end with a link to the information page called "Quotes within Quotes."_

There **should be** a link to a tA Topic about 'Direct or Indirect Quotations' or 'Quotes within Quotes.'

**Comment by ChrisJarka** [comment]
**Notes with Possible Meanings**

See: https://git.door43.org/Door43/en_ta/src/master/translate/resources-porp/01.md

The formatting is:
_Our notes for these situations begin with "Possible meanings are" and then give a numbered list._

These are described as:
_Sometimes Bible scholars do not know for sure, or do not agree on, what a particular phrase or sentence in the Bible means. Some reasons for this include:_

- _There are minor differences in the ancient Bible texts._
- _A word may have more than one meaning or use._
- _It may not be clear what a word (such as a pronoun) refers to in a particular phrase._

An example is:

- **fell down at Jesus' knees** - Possible meanings are 1) "knelt down before Jesus" or 2) "bowed down at Jesus feet" or 3) "lay down on the ground at Jesus feet." Peter did not fall accidentally. He did this as a sign of humility and respect for Jesus.

**Comment by ChrisJarka** [comment]
**Notes with Synonyms and Equivalent Phrases**

Described on page: https://git.door43.org/Door43/en_ta/src/master/translate/resources-synequi/01.md

as:
_Some Notes provide a translation suggestion that can replace the word or phrase that they quote from the ULB. These replacements can fit into the sentence without changing the meaning of the sentence. These are synonyms and equivalent phrases and are written in double-quotes. These mean the same as the text in the ULB. This kind of Note can help you to think of other ways to say the same thing, in case the word or phrase in the ULB does not seem to have a natural equivalent in your language._

The standard formatting is:
_These are synonyms and equivalent phrases and are written in double-quotes._

Examples:

- Deacons, likewise - "In the same way, deacons" or "Deacons, like overseers"
- the way - "the path" or "the road"

**Comment by ChrisJarka** [comment]
There is also this page: https://git.door43.org/Door43/en_ta/src/master/translate/resources-long/01.md that describes how the long snippet with short snippets following are related.

_Sometimes there are notes for a phrase and separate notes for portions of that phrase. In that case, the larger phrase is explained first, and its parts afterward._

**Comment by ChrisJarka** [comment]
There is one page that describes the links found in the notes: https://git.door43.org/Door43/en_ta/src/master/translate/resources-links/01.md

**Figures of Speech (Just In Time Learning tA Topics)** -
_Each translationNote follows a phrase from the ULB and will provide immediate help on how to translate that phrase. Sometimes there will be a statement in parenthesis at the end of the suggested translation that may look like this: (See: Metaphor). The word or words in green are a link to a translationAcademy topic. You can click on the link to learn more about the topic._

**Repeated Phrases in a Book** -
_Sometimes a phrase is used multiple times in one book. When this happens, there will be a link in the translationNotes-green chapter and verse numbers that you can click on-that will take you back to where you have translated that phrase before. _

**Comment by pjoakes** [comment]
Most of these Notes topics have much more value for translating than for checking. They belong in tS, but not necessarily in tC. For example, a suggestion of alternate ways to translate (AT) is helpful to the translator but not so much to the checker.  Also, I would expect the translation team to decide on which interpretation to follow when translating when there are differences of scholarly opinion (Alternate Meaning), but after they have made that choice the checking team shouldn’t have to revisit that, only make sure that they translated according to that meaning.
The useful topics might be:
Word/phrase definitions. These are not in tW because they occur very few times.
Direct and indirect quotes. But I thought this was already a tN category in tC.
Repeated phrases. It would be great to be able to check these against each other.

**Comment by jag3773** [comment]
A multi-pronged approach is planned for addressing these:

1. Word/Phrase definitions: https://git.door43.org/unfoldingWord/en_tn/issues/1074
2. Direct and indirect: already completed
3. Repeated phrases: planned to be encoded in our Greek and Hebrew texts, seeded by a mashup of our tN notes that follow that format and a search.
