### ISSUE TITLE
Some Footnotes Not Rendering Properly

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#710]
The Footnotes of LUK 2:22, and LUK 2:33 are not rendering properly in the rendered version found: 
https://live.door43.org/u/Door43/en_ulb/c0bd11bad0/43-LUK.html#ref-fn-042-002-022-1 . Portions of the note are carried into the USFM formatted text. Perhaps the comma in the Footnote is confusing for the rendering engine.

There are ULB ISSUES on this: https://git.door43.org/Door43/en_ulb/issues/1193 and https://git.door43.org/Door43/en_ulb/issues/1194

**Comment by ChrisJarka** [comment]
@jag3773 I think that the title of this issue should be changed by removing the e on Note. :)

**Comment by ChrisJarka** [comment]
Also in 1CH 3:5
USFM:
5 These four sons, by Bathsheba daughter of Ammiel, were born to him in Jerusalem: Shammua, Shobab, Nathan, and Solomon.
\f + \ft Some versions have \fqa Bathseba \fqa* or \fqa Bathshua \fqa* instead of \fqa Bathsheba \fqa* . \f*
\s5
\v 6 David's other nine sons were: Ibhar, Elishua, Eliphelet,

Live door43
 These four sons, by Bathsheba daughter of Ammiel, were born to him in Jerusalem: Shammua, Shobab, Nathan, and Solomon. [ 1 ] or instead of .

**Comment by SusanQuigley** [comment]
JOS 5:1
USFM
\c 5
\p
\v 1 As soon as all the kings of the Amorites on the west side of the Jordan, and all the kings of the Canaanites, who were along the coast of the Great Sea, heard that Yahweh had dried up the waters of the Jordan until the people of Israel had crossed over, their hearts melted, and there was no longer any spirit in them because of the people of Israel.
\f + \ft Some modern versions have: \fqa until the people of Israel had crossed over, \fqa* and others have, \fqa until we had crossed over. \fqa* The Hebrew text has \fqa we, \fqa* but a note in the margin instructs readers to say \fqa they. \fqa* Translators can decide for themselves. \f*

The footnote appears at the end of the chapter, but it is missing material:  
5:1 [ 1 ] Some modern versions have: until the people of Israel had crossed over, until we had crossed over. we, they.

Could it be that at this point the program can handle only one \fqa ... \fqa* set in a footnote?

**Comment by SusanQuigley** [comment]
Other footnotes in the ULB showing up at the end of the chapter, but missing information. 

**JOS 9:4**
\f + \ft Instead of \fqa They went as messengers, \fqa* some versions have, \fqa They got provisions ready. \fqa* \f*
**live.door43**  
9:4 [ 1 ] Instead of They went as messengers, They got provisions ready.

**RUT 3:3**  
\f + \ft The Hebrew text has, \fqa Put on your best piece of clothing. \fqa* However, a marginal note instructs readers to read, \fqa Put on your best clothes. \fqa* Translators are free to choose for themselves. \f*
**live.door43**  
3:3 [ 1 ] The Hebrew text has, Put on your best piece of clothing. Put on your best clothes.

**1SA 1:1**  
\f + \ft Some modern versions have \fqa Ramathaim Zophim, \fqa* but it is understood that \fqa Zophim \fqa* really refers to the region in which the clan descended from Zuph resided. \f*  
**live.door43**
1:1 [ 1 ] Some modern versions have Ramathaim Zophim, Zophim

**1SA 1:24**
\f + \ft Some translations have \fqa three bulls \fqa* instead of \fqa a three-year-old bull. \f* 
**live.door43**  
1:24 [ 2 ] Some translations have three bulls a three-year-old bull.

Since the ULB has 338 footnotes and 427 footnotes with \fqa*, I suspect there may be about a hundred notes with two or more \fqa ... \fqa* sets.

**Comment by SusanQuigley** [comment]
In live.door 43, I have not come across any material in an \fqa ... \fqa* set showing up as italics.

**Comment by DavidHaslam** [comment]
References to "red text" are lost on your readers. Nothing is rendered red in this thread.
Had you used the grave accent as the Markdown code formatting available in this Git, then perhaps some text might display as red, but only because of a flook whereby Git expects to highlight some code with red text.
```
\f + \ft Some older versions have, \fqa the bronze altar made by Bezalel son of Uri son of Hur, he placed there before the tabernacle of Yahweh \fqa* , where \fqa he \fqa* refers to David. \f*
Some older versions have, the bronze altar made by Bezalel son of Uri son of Hur, he placed there before the tabernacle of Yahweh, where he refers to David.
```

Why do so few contributors use **Markdown** in issues and comments?  It's not difficult to learn.

**Comment by jag3773** [comment]
Just an update for those following this thread, we should have the fix deployed to the site next week.

**Comment by TomWarren** [comment]
FYI, I have been editing the Footnotes in line with the corrections that Richard sent to me. (chiefly, removing a period before the \fqa, and the repositioning the period to be between the \fqa* and the \f*. 
About 130 of these were found.

Tom Warren

**Comment by TomWarren** [comment]
And I read through all the footnotes in the ULB to check for obvious errors, finding about 10 or so that were clearly mistakes of syntax.

Tom
