### ISSUE TITLE
Update Links to CDN

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#72]
We need to start pointing the URLs in the catalog for audio/video to cdn.door43.org.

After we update the links everywhere that we know about them, then we want to setup Nginx redirects that take api.uw links for the audio/video and redirect them to the appropriate cdn.door43.org location.

We should also CNAME cdn.uw to cdn.door43 if all the links checkout correctly.

Related issue https://github.com/unfoldingWord/unfoldingWord.github.io/issues/154 .

**Comment by neutrinog** [comment]
This seems like a good place to note that media support has been implemented in the api. However, aws lambda instances are limited in size (512mb) so large files (like a zip of movie files) will break the lambda function.

I've provided a work around that will simply skip signing these large files and wait for signatures to be manually uploaded. Currently we only experience this problem when signing these two files:

* https://cdn.door43.org/en/obs/v4/360p/en_obs_360p.zip
* https://cdn.door43.org/en/obs/v4/720p/en_obs_720p.zip

Since media files will be changed infrequently this seems like a reasonable solution for now. If we need to re-address this we could attempt to increase the lambda instance size or set up a dedicated server for signing.
