### ISSUE TITLE
OBS stories missing on Door43 Browse

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord-dev/door43.org#783]
The May 17th revision of the OBS caused the stories to stop displaying on https://door43.org/u/Door43/en-obs/20a80eddbd/index.html.  They were OK before that revision. Front and Back pages show, but not the chapters.

**Comment by jag3773** [comment]
Hi @lrsallee, this actually because we changed the name of the repository from a - to an _ as the separator between the language and resource type.  The latest OBS is available at https://door43.org/u/Door43/en_obs/ .

However, you probably got there because the old one is still showing up in the search results. We will fix this so that the old one is no longer available, instead it will redirect to the new one.

**Comment by lrsallee** [comment]
I got here by using the "Browse" button on https://door43.org/. It was my understanding that this is the newest site, and that this would (eventually) allow us to see the formatted version of all the resources. When I browsed to the OBS, I clicked on the latest version that appears on the page. However, the two latest do not display.

Should I not be using this site in this way?

**Comment by jag3773** [comment]
You are doing it exactly correct.  We had old data in the database that was providing links to the old content.

I have fixed the immediate issue, you will not see the old data in the Browse or search results anymore.

**Comment by lrsallee** [comment]
Thanks, Jesse. Looks good now. There are a few warning messages that refer to minor formatting issues. Nothing critical.
