### ISSUE TITLE
Revise Revisions

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#822]
Instead of providing access to every build that happens it would be more natural and clean up the page if we just provided the latest build for each repo.  This would also reduce the clutter of unused data being stored.

This should be implemented with #33  so that users can persist builds by means of marking their content with a release in DCS.

## Notes

URL endpoints should be something like this:

* /latest/ - most recent commit on the default branch always gets processed here
* /[branch_name]/ - most recent commit on the named branch always gets processed here
* /[tag]/ - any tagged commit is built and persisted here

**Comment by RobH123** [comment]
@jag3773 Looking at this and at #33 and trying to understand how it's all going to work, what steps do you envision to get there?

1/ Currently we're only notified of a push by the webhook. I think that can remain the same (but how do we get notified about new tags)?
2/ We currently ignore pushes to other than the default branch (usually master). I think now we want to process all branches, but treat master differently (it goes to /latest/ rather than /master/)?
3/ I can see tags with curl -X GET "https://git.door43.org/api/v1/repos/unfoldingWord/en_obs/releases" -H  "accept: application/json" and that leads to a zipball_url field so I can fetch the repo for a tag, but again the question: How do I get notified that a new tag has been pushed?

**Comment by jag3773** [comment]
@RobH123 

1. We can change the webhooks to notify on all events.  This should give you the data you need, including when a release tag is created.
2. Correct, we'll want to process all branches.  However, note that the branch specified as the *default branch* in the payload should appear at the /latest/ endpoint.  Normally this is the `master` branch but users can configure this per repo and the payload tells you what it's set to.
3. Seems like a good idea to have the ability to trigger a listing of a repo's releases to build all of them.  This could be useful if only in the short term to troll back through and get the releases built?

**Comment by RobH123** [comment]
@jag3773 Looking at this and at #33 and trying to understand how it's all going to work, what steps do you envision to get there?

1/ Currently we're only notified of a push by the webhook. I think that can remain the same (but how do we get notified about new tags)?
2/ We currently ignore pushes to other than the default branch (usually master). I think now we want to process all branches, but treat master differently (it goes to /latest/ rather than /master/)?
3/ I can see tags with curl -X GET "https://git.door43.org/api/v1/repos/unfoldingWord/en_obs/releases" -H  "accept: application/json" and that leads to a zipball_url field so I can fetch the repo for a tag, but again the question: How do I get notified that a new tag has been pushed?

**Comment by jag3773** [comment]
@RobH123 I think we need to add a tooltip/hover over on the "Updated X minutes ago" text that shows the git commit hash.  Currently we can't see the hash anywhere which will make debugging difficult.
