### ISSUE TITLE
Door43 Jobs: Track invocations by user & repo 

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#839]
In the Door43 enqueue service I'd like to start tracking unique repo invocations.  Currently we are gleaning this information from the tx.jobs database table but we'll hopefully be getting rid of that eventually.  The information is best tracked in the Door43 Jobs side of the picture anyway.

I think that these two would give us what we need:

* `door43.[prod|dev].enqueue-job.users.invoked.(username)`: This should use the `repository.owner.full_name` field from the payload.
* `door43.[prod|dev].enqueue-job.user-projects.invoked.(username)/(reponame)`: This should use the `repository.full_name` field from the payload if `/` characters are allowed.  If they are not, then replace the `/` with a `-`.

**Comment by RobH123** [comment]
Implemented in dev- chain. Seems that stats automatically replaces / with hyphen. I wonder if two hyphens or something else might be better (since usernames and/or repo_names could already contain hyphens)?

I added the current fields to my comment at the bottom of https://github.com/unfoldingWord-dev/door43.org/issues/837

**Comment by jag3773** [comment]
Looks ok to me as is.  I'm not sure we could find a character that is allowed for graphite but disallowed for a DCS username...
