### ISSUE TITLE
Deprecate `modules` table

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#842]
The `modules` database table is no longer needed since we are now using a unified codebase for tX.  Seems more reasonable to put this information directly into the code.

**Comment by RobH123** [comment]
Done in tX Job Handler. Tested on a range of repos.

New tables can be seen at https://github.com/unfoldingWord-dev/tx-job-handler/blob/master/webhook.py#L39

Note that I add a couple of extra fields: I tried putting 'txt' through markdown linter, and added 'ult' and 'ust' to usfm2html converter, although it makes little difference since they are covered by 'other' anyway.
