### ISSUE TITLE
Improve Resource Container Identification

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#850]
As projects comes into the system they should be identified for conversion by the `subject` field in the manifest.yaml.

See the list of resources at https://api.door43.org/v3/subjects .

**Comment by RobH123** [comment]
So I presume that this should lead to the removal of the "resource_map" from here: https://github.com/unfoldingWord-dev/door43-job-handler/blob/master/resource_container/ResourceContainer.py#L15 ?

**Comment by RobH123** [comment]
@jag3773  The RC code also contains a table for file extensions: https://github.com/unfoldingWord-dev/door43-job-handler/blob/master/resource_container/ResourceContainer.py#L405

Should/Could that be included in the RC manifest instead?

**Comment by RobH123** [comment]
@jag3773 Did a previous version of RC use a different manifest format, e.g., this one: https://git.door43.org/RobH/tem_obs_text_obs/src/branch/master/manifest.json

This is one of the cases where tx-Manager used an internal fixed resource_map table to determine the type as 'book', cf., 	"type": {
		"id": "text",
		"name": "Text"
	}

**Comment by RobH123** [comment]
@jag3773 I commented out the resource_map, and the only negative effect that I could discover was some tN resources not getting a full title (so they display a title of 'tN' identifier instead of 'translationNotes') like this one: https://dev.door43.org/u/RobH/plt_1co_tn/1b08def227/

So I think I'm ready to risk removing that hard-coded resource_map out of the code.

Would it be worth displaying a warning (even error???) for a repo that doesn't have a manifest.yaml to encourage people to upgrade?

**Comment by RobH123** [comment]
Oh, I discovered more Bible versions hardcoded in here: https://github.com/unfoldingWord-dev/tx-job-handler/blob/master/resource_container/ResourceContainer.py#L376

elif 'slug' in self.resource and self.resource['slug']:
            slug = self.resource['slug'].lower()
            if 'ulb' in slug:
                return 'ulb'
            elif 'udb' in slug:
                return 'udb'
            elif 'obs' in slug:
                return 'obs'
            else:
                return slug
        elif 'ulb' in self.rc.repo_name.lower():
            return 'ulb'
        elif 'udb' in self.rc.repo_name.lower():
            return 'udb'
        elif 'obs' in self.rc.repo_name.lower():
            return 'obs'

**Comment by RobH123** [comment]
Ok, I removed pretty much all of the tx-manager hard-coded stuff in ResourceContainer.py and tested thoroughly on the dev- chain. I'll submit PRs and then this can probably be closed I think.

**Comment by RobH123** [comment]
@jag3773 Looking at this again, I've removed hard-coded resource types from (what was the tx Manager) RC code, but I haven't actually used the subject fields.

The Door43 system currently passes the following to the tX system: *input_format* (e.g., md, usfm, tsv), *output_format* (html), and *resource_type* (e.g., obs, ta, tn, tq, tw, bible). Those three fields are what's used to determine linter and converter.

I think the above system is working ok at present. Do you think we really want/need the RC subject to be passed through the system? (Will it be necessary for future improvements/extensions?)

**Comment by jag3773** [comment]
@RobH123 We'll want both to be in effect for determining _resource_type_ :

1. First, check if the subject field matches a known _resource_type_, else
2. Check if the id matches a known _resource_type_

Going forward the `id`s are going to be more diverse but the subject fields will be standard (for the resources published in the catalog).  Here is the list of subjects currently in the catalog: https://api.door43.org/v3/subjects .  This will be essential to be able to distinguish between an "Aligned Bible" and a "regular" Bible, for instance.  Or between a "Hebrew Old Testament" and an "Aligned Bible".  Of course, tX will need to know this in order to process the USFM correctly and put the right information into the HTML files.

Does that make sense?

**Comment by RobH123** [comment]
@jag3773 I looked at the subjects of my 52 assorted test repos. I got:
Bible stories
Open Bible Stories
Unlocked Literal Bible
en_ulb_full
ULT Revelation
Unlocked Dynamic Bible
Russian Synodal Bible
Bible
Aligned Bible
Hebrew Old Testament
Greek New Testament
alignedudt_en
alignedulb_hi_test
Nepali ULB
Translator Notes/Questions
Translation Notes/Questions/Words/Academy
tn
Bible translation comprehension questions
(empty)
Note that existing code to fetch RC subject, fetches the title if there's no subject, so that explains some of the above.

Seems a bit messy with case (stories vs Stories), with a lot of variety for Bibles, and with Translation vs Translator.

This is going to be messy to program.
Is the word 'Subject' misleading? Would Category be a better word? ('resource_type' is the name of the current field passed from Door43 Job Handler to tX part.)
Does 'Open' have to be in subject for 'Bible Stories'? (Couldn't 'Open' bit just be in Title?)

**Comment by jag3773** [comment]
@RobH123 The only ones that constitute a match are those listed in https://api.door43.org/v3/subjects (the _ stands for a space).

**Comment by RobH123** [comment]
@jag3773 This is done now. Once you've read/addressed the above comment, you can close this issue I think.

**Comment by jag3773** [comment]
@RobH123 Good catch, I've got that fixed now.
